### ISSUE TITLE
Syntax error + advanced fuzzing mode

### ISSUE THREAD

**Issue by lexylee2406** [sslab-gatech/freedom#2]
Hello,

Thank you very much for making FreeDom open source.

I have just tried to test it on Ubuntu 18.04 following the commands in README but it doesn't work.

In mode 0 (test case generation only), I received the following error message:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from attribute.html import initialize_html_attributes
  File "/home/ubuntu/freedom/attribute/__init__.py", line 3, in <module>
    from utils.random import Random
  File "/home/ubuntu/freedom/utils/__init__.py", line 4
    def cat(args: [str]) -> str:
                ^
SyntaxError: invalid syntax
```
This might be a OS-specific issue. If so, what are the operating systems on which FreeDom has been successfully tested?

Moreover, could you please update your README to include commands to run FreeDom in the more advanced mode with code coverage guidance as explained in the paper.

LL.

**Comment by adrian-rt** [comment]
+1 for "Moreover, could you please update your README to include commands to run FreeDom in the more advanced mode with code coverage guidance as explained in the paper."

thanks.

**Comment by lexylee2406** [comment]
Ah, I got the syntax error as reported above because I used python instead of python3.

So the command in the README should be corrected as follows

```
python3 main.py -i 1 -m generate -n 10 -o output
```

Instead of 

```
python main.py -i 1 -m generate -n 10 -o output
```
